[package]
name = "e2e-skills-intro"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fframes = { version = "=1.2.0", features = ["compile-time-svgtree", "cli"] }

[target.'cfg(not(windows))'.dependencies]
fframes = { version = "=1.2.0", features = ["h264", "libav-agree-gpl"] }

[lib]
name = "e2e_skills_intro"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "e2e-skills-intro"
path = "src/main.rs"

[workspace]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
