#!/usr/bin/env python3
"""Mechanical helpers for the end-to-end-development coordinator.

The helpers deliberately contain no product judgment. They classify an already
identified risk set, fingerprint a Git worktree, supervise immutable worker
assignments, render accepted artifacts, and summarize run timing.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import os
import re
import subprocess
import sys
import tempfile
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

# The skill directory is copied into the user's config tree. Avoid leaving
# generated bytecode there when this helper imports the sibling validator.
sys.dont_write_bytecode = True

import artifact_guard  # noqa: E402
import delivery_tools  # noqa: E402
import worker_supervisor  # noqa: E402

FORCE_FULL_RISKS = {
    "authorization",
    "background-processing",
    "concurrency",
    "data-backfill",
    "database-migration",
    "high-cost-mechanism",
    "new-storage",
    "public-interface",
    "security",
}

WORKER_RUNTIMES = {"auto", "codex", "pi"}
DEFAULT_WORKER_MODEL = worker_supervisor.DEFAULT_WORKER_MODEL
DEFAULT_WORKER_THINKING = worker_supervisor.DEFAULT_WORKER_THINKING


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def atomic_write_json(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    temporary.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def workflow_policy(
    *,
    repository_count: int,
    risk_flags: Iterable[str],
    requested_profile: str = "auto",
    report_requested: bool = False,
) -> dict[str, Any]:
    if repository_count < 1:
        raise ValueError("repository_count must be at least one")
    flags = sorted(set(risk_flags))
    unknown = set(flags) - artifact_guard.RISK_FLAGS
    if unknown:
        raise ValueError(f"unknown risk flags: {sorted(unknown)}")
    if requested_profile not in {"auto", *artifact_guard.PROFILES}:
        raise ValueError(f"unknown profile: {requested_profile}")

    full_reasons = [
        f"high-risk surface: {flag}"
        for flag in sorted(set(flags) & FORCE_FULL_RISKS)
    ]

    if requested_profile == "full" or full_reasons:
        profile = "full"
    elif requested_profile == "fast" and (flags or repository_count > 1):
        profile = "standard"
    elif requested_profile == "fast":
        profile = "fast"
    else:
        # Fast is opt-in. Standard also coordinates ordinary multi-repository
        # work; repository count alone is not a reason to enable every
        # high-assurance worker and human gate.
        profile = "standard"

    reasons = list(full_reasons)
    if repository_count > 1 and not full_reasons:
        reasons.append("ordinary multi-repository coordination")
    if requested_profile != "auto":
        reasons.append(f"requested profile: {requested_profile}")
    if not reasons:
        reasons.append("single-repository change with no declared high-risk surface")
    if requested_profile == "fast" and profile != "fast":
        reasons.append(
            f"fast request automatically escalated to {profile}; "
            "safety profiles cannot be weakened"
        )

    multi_repository = repository_count > 1
    policies: dict[str, dict[str, Any]] = {
        "fast": {
            "contract_required": False,
            "design_challenge": "none",
            "integration_required": False,
            "report_required": report_requested,
            "max_tasks_per_packet": 4,
            "max_packet_minutes": 45,
            "second_review": "never",
            "blocking_severities": ["critical", "high", "medium"],
            "coordinator_attempt_budget": 30,
            "auto_resume": True,
            "user_plan_approval_required": False,
        },
        "standard": {
            "contract_required": multi_repository,
            "design_challenge": "risk-only",
            "integration_required": multi_repository,
            "report_required": report_requested,
            "max_tasks_per_packet": 3,
            "max_packet_minutes": 45,
            "second_review": "never",
            "blocking_severities": ["critical", "high", "medium"],
            "coordinator_attempt_budget": 30,
            "auto_resume": True,
            "user_plan_approval_required": False,
        },
        "full": {
            "contract_required": multi_repository,
            "design_challenge": "risk-only",
            "integration_required": multi_repository,
            "report_required": report_requested,
            "max_tasks_per_packet": 3,
            "max_packet_minutes": 45,
            "second_review": "never",
            "blocking_severities": ["critical", "high", "medium"],
            "coordinator_attempt_budget": 30,
            "auto_resume": True,
            "user_plan_approval_required": True,
        },
    }
    result = {
        "profile": profile,
        "profile_reasons": reasons,
        "risk_flags": flags,
        "workflow_policy": policies[profile],
    }
    artifact_guard.validate_workflow_policy(
        result["workflow_policy"], profile, "$.workflow_policy"
    )
    return result


def _git(
    worktree: Path, *args: str, env: dict[str, str] | None = None
) -> bytes:
    process = subprocess.run(
        ["git", "-C", str(worktree), *args],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
    )
    if process.returncode != 0:
        raise RuntimeError(
            f"git {' '.join(args)} failed in {worktree}: "
            f"{process.stderr.decode('utf-8', errors='replace').strip()}"
        )
    return process.stdout


def worktree_fingerprint(worktree: Path) -> str:
    """Preserve the public v3 fingerprint seam shared with standalone delivery."""
    return delivery_tools.content_fingerprint(worktree)


def repository_state(worktree: Path) -> dict[str, str]:
    """Pin content and semantic Git state without depending on index stat-cache bytes."""
    return {
        "fingerprint": worktree_fingerprint(worktree),
        "head": _git(worktree, "rev-parse", "HEAD").decode().strip(),
        "branch": _git(worktree, "branch", "--show-current").decode().strip(),
        "index_sha256": hashlib.sha256(_git(worktree, "ls-files", "--stage", "-z")).hexdigest(),
    }


def artifact_evidence_paths(value: Any) -> set[Path]:
    """Collect on-disk evidence, not narrative strings or arbitrary source paths."""
    paths: set[Path] = set()
    if isinstance(value, dict):
        for key, child in value.items():
            if key in {"evidence_path", "log_path", "status_short_path"} and isinstance(child, str):
                paths.add(Path(child).resolve())
            elif key == "source_artifact" and isinstance(child, dict):
                paths.add(Path(child["path"]).resolve())
            else:
                paths.update(artifact_evidence_paths(child))
    elif isinstance(value, list):
        for child in value:
            paths.update(artifact_evidence_paths(child))
    return paths


def normalize_worker_artifact(
    assignment_path: Path,
    assignment: dict[str, Any],
    output_path: Path,
    artifact: dict[str, Any],
    *,
    persist: bool = True,
) -> dict[str, Any]:
    """Attach mechanically verifiable repository evidence before acceptance.

    persist=False computes the same metadata without writing output/status files,
    allowing recovery to reject ambiguous existing evidence before any mutation.

    Workers own semantic conclusions. The coordinator owns hashes, Git state,
    and status snapshots so a correct result is not retried because a model
    copied stale mechanical metadata into its JSON artifact.
    """
    if assignment.get("execution_mode") == "artifact-repair":
        for repository in assignment["repositories"]:
            expected = assignment["repair_of"]["repository_states"][repository["repo_id"]]
            if repository_state(Path(repository["worktree"])) != expected:
                raise artifact_guard.ValidationError("artifact-only repair changed pinned repository/Git state")
    resolved_assignment = assignment_path.resolve()
    artifact["assignment_path"] = str(resolved_assignment)
    artifact["assignment_sha256"] = hashlib.sha256(
        resolved_assignment.read_bytes()
    ).hexdigest()
    if assignment.get("repo_id") is None:
        if persist:
            atomic_write_json(output_path, artifact)
        return artifact
    worktree = Path(assignment["cwd"])
    if not (worktree / ".git").exists():
        # Standalone artifact-validation fixtures may intentionally use a plain
        # directory. Initialized workflow repositories are always Git worktrees.
        if persist:
            atomic_write_json(output_path, artifact)
        return artifact
    _git(worktree, "rev-parse", "--show-toplevel")
    current_fingerprint = worktree_fingerprint(worktree)
    expected_fingerprint = assignment.get("input_tree_fingerprint")
    if (
        assignment.get("project_file_access") != "write"
        and expected_fingerprint is not None
        and expected_fingerprint != current_fingerprint
    ):
        raise artifact_guard.ValidationError(
            "read-only worker changed repository content after assignment creation"
        )
    log_dir = Path(assignment["log_dir"])
    if persist:
        log_dir.mkdir(parents=True, exist_ok=True)
    status_path = log_dir / f"{output_path.stem}-coordinator-status.txt"
    status = _git(worktree, "status", "--short").decode(
        "utf-8", errors="replace"
    )
    if persist:
        status_path.write_text(status.rstrip("\n") + "\n", encoding="utf-8")

    if artifact.get("artifact_kind") == "result":
        fingerprint = current_fingerprint
        artifact["tree_fingerprint"] = fingerprint
        artifact["git"] = {
            "head": _git(worktree, "rev-parse", "HEAD").decode().strip(),
            "status_short_path": str(status_path.resolve()),
        }
        for record in artifact.get("validations", []):
            if not isinstance(record, dict) or not isinstance(record.get("command"), str):
                continue
            command = record["command"]
            record["command_sha256"] = hashlib.sha256(command.encode()).hexdigest()
            if record.get("cache_status") != "reused":
                record["tree_fingerprint"] = fingerprint
                record.setdefault("cache_status", "fresh")
                record.setdefault("source_artifact", None)
    elif artifact.get("artifact_kind") == "review":
        artifact["baseline"] = assignment["baseline"]
        artifact["reviewed_status_path"] = str(status_path.resolve())

    if persist:
        atomic_write_json(output_path, artifact)
    return artifact


def _parse_timestamp(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def _union_minutes(intervals: list[tuple[datetime, datetime]]) -> float:
    if not intervals:
        return 0.0
    ordered = sorted(intervals)
    start, end = ordered[0]
    total = 0.0
    for next_start, next_end in ordered[1:]:
        if next_start <= end:
            end = max(end, next_end)
        else:
            total += (end - start).total_seconds() / 60
            start, end = next_start, next_end
    return total + (end - start).total_seconds() / 60


def run_metrics(run_dir: Path) -> dict[str, Any]:
    run = load_json(run_dir / "run.json")
    agents = load_json(run_dir / "agents.json").get("agents", [])
    events: list[dict[str, Any]] = []
    event_path = run_dir / "events.jsonl"
    if event_path.exists():
        for line in event_path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                events.append(json.loads(line))

    by_stage: dict[str, list[tuple[datetime, datetime]]] = defaultdict(list)
    all_intervals: list[tuple[datetime, datetime]] = []
    for agent in agents:
        if not agent.get("started_at") or not agent.get("ended_at"):
            continue
        interval = (_parse_timestamp(agent["started_at"]), _parse_timestamp(agent["ended_at"]))
        all_intervals.append(interval)
        by_stage[str(agent["stage"])].append(interval)

    stages: dict[str, Any] = {}
    for stage, intervals in sorted(by_stage.items()):
        stages[stage] = {
            "attempts": len(intervals),
            "worker_minutes_sum": round(
                sum((end - start).total_seconds() / 60 for start, end in intervals), 2
            ),
            "active_minutes_union": round(_union_minutes(intervals), 2),
        }
    created = _parse_timestamp(run["created_at"])
    updated = _parse_timestamp(run["updated_at"])
    return {
        "schema_version": 1,
        "run_id": run["run_id"],
        "generated_at": utc_now(),
        "wall_minutes": round((updated - created).total_seconds() / 60, 2),
        "active_worker_minutes": round(_union_minutes(all_intervals), 2),
        "worker_attempts": len(agents),
        "command_attempts": sum(event.get("event") == "command-started" for event in events),
        "resumes": sum(event.get("event") == "resumed" for event in events),
        "blocked_events": sum(event.get("event") == "blocked" for event in events),
        "event_counts": dict(
            sorted(Counter(str(event.get("event", "unknown")) for event in events).items())
        ),
        "stages": stages,
    }


def _agent_name(assignment: dict[str, Any]) -> str:
    """Build a deterministic Herdr-safe name without truncating its identity hash."""
    identity = json.dumps(
        [assignment["run_id"], assignment["action_id"], assignment["attempt"]],
        separators=(",", ":"),
    )
    digest = hashlib.sha256(identity.encode()).hexdigest()[:8]
    suffix = f"-{digest}-a{assignment['attempt']}"
    # Attempts have no schema upper bound; the hash still identifies huge ones.
    if len(suffix) > 28:
        return f"e2e-{digest}"
    repo = assignment.get("repo_id") or "global"
    label = re.sub(r"[^a-z0-9_-]+", "-", f"{repo}-{assignment['stage']}".lower())
    prefix = f"e2e-{label}"[: 32 - len(suffix)].rstrip("-_")
    return prefix + suffix


def _legacy_agent_name(assignment: dict[str, Any]) -> str:
    """Only for adopting workers launched before bounded names were introduced."""
    action_hash = hashlib.sha256(assignment["action_id"].encode()).hexdigest()[:8]
    repo = assignment.get("repo_id") or "global"
    prefix = assignment["run_id"].split("-")[0]
    return f"{prefix}-{repo}-{assignment['stage']}-{action_hash}-a{assignment['attempt']}"


def _worker_prompt(assignment_path: Path) -> str:
    return (
        f"Execute the immutable assignment at {assignment_path}. Treat its hash-pinned inputs "
        "as authoritative. If the output does not exist, initialize its stage-specific skeleton "
        "with the assignment's validator init command. Read artifact_schema_path and its linked blocker "
        "contract, not the full coordinator contract. Write only the assigned output, allowed project files, and "
        "log directory. Complete semantic fields and command outcomes; do not spend time "
        "recomputing assignment, Git-status, content-fingerprint, or command hashes because the "
        "coordinator normalizes and validates those after settlement. Do not spawn nested agents. "
        "Final response: at most eight lines containing status, output path, and blocker IDs."
    )


def _resolve_worker_runtime(runtime: str = "auto") -> str:
    """Select the worker CLI from the current coordinator runtime.

    The explicit argument wins, followed by the environment override. In
    auto mode, Codex's thread marker is the reliable signal available to
    subprocesses; ordinary Pi invocations fall back to the Pi worker.
    """
    selected = runtime.strip().lower()
    if selected not in WORKER_RUNTIMES:
        raise ValueError(f"unknown worker runtime: {runtime}")
    if selected == "auto":
        selected = os.environ.get("E2E_COORDINATOR_RUNTIME", "auto").strip().lower()
        if selected not in WORKER_RUNTIMES:
            raise ValueError(
                "E2E_COORDINATOR_RUNTIME must be one of: auto, codex, pi"
            )
    if selected == "auto":
        selected = "codex" if os.environ.get("CODEX_THREAD_ID") else "pi"
    return selected


def _enforce_user_plan_approval(
    run: dict[str, Any],
    assignments: list[tuple[Path, dict[str, Any]]],
) -> None:
    writers = [
        (path, assignment)
        for path, assignment in assignments
        if assignment.get("project_file_access") == "write"
    ]
    if not writers:
        return

    review = run.get("plan_review")
    if not isinstance(review, dict) or review.get("status") != "approved":
        raise ValueError(
            "project-file writers are forbidden until the workflow records an approved "
            "plan decision bundle"
        )
    if artifact_guard.PHASE_ORDER.index(run["phase"]) < artifact_guard.PHASE_ORDER.index(
        "implement"
    ):
        raise ValueError("project-file writers are forbidden before the implement phase")

    expected_path = review.get("review_path")
    expected_hash = review.get("review_sha256")
    if not isinstance(expected_path, str) or not isinstance(expected_hash, str):
        raise ValueError("approved plan review is missing its bundle path or hash")
    expected_resolved = Path(expected_path).resolve()
    for assignment_path, assignment in writers:
        reference = assignment.get("plan_review")
        if not isinstance(reference, dict):
            raise ValueError(
                f"project-file assignment {assignment_path} does not pin the approved "
                "plan review bundle"
            )
        reference_path = reference.get("path")
        reference_hash = reference.get("sha256")
        if (
            not isinstance(reference_path, str)
            or Path(reference_path).resolve() != expected_resolved
            or reference_hash != expected_hash
        ):
            raise ValueError(
                f"project-file assignment {assignment_path} does not match the approved "
                "plan review bundle"
            )


def effective_thinking(assignment: dict[str, Any], run: dict[str, Any]) -> str:
    policy = assignment.get("reasoning_policy", run.get("worker_reasoning_policy", "legacy-xhigh"))
    return worker_supervisor.runtime_thinking(str(assignment.get("thinking", "xhigh")), policy=policy)


def recover_assignment_worker(
    assignment_path: Path,
    assignment: dict[str, Any],
    *,
    run_dir: Path,
) -> dict[str, Any] | None:
    """Adopt and settle a previously launched worker through its recorded backend."""
    record_path = (
        run_dir
        / "supervisor"
        / worker_supervisor.WorkerSupervisor.record_name(assignment["action_id"])
    )
    record: dict[str, Any] | None = None
    if record_path.is_file():
        try:
            value = json.loads(record_path.read_text(encoding="utf-8"))
            if isinstance(value, dict):
                record = value
        except (OSError, json.JSONDecodeError):
            record = None
    run_path = run_dir / "run.json"
    run = load_json(run_path) if run_path.is_file() else {}
    pinned = run.get("worker_execution")
    if record and isinstance(record.get("backend"), str):
        backend = record["backend"]
        runtime = str(record.get("runtime") or "pi")
        detected_from = "supervisor-record"
        evidence: dict[str, Any] = {}
    elif isinstance(pinned, dict):
        backend = pinned["backend"]
        runtime = pinned["runtime"]
        detected_from = pinned.get("detected_from", "run.json")
        evidence = dict(pinned.get("evidence", {}))
    else:
        # Older runs were exclusively Herdr-managed and have no generic record.
        backend = "herdr"
        runtime = _resolve_worker_runtime("auto")
        detected_from = "schema-v1-herdr"
        evidence = {}
    context = worker_supervisor.ExecutionContext(
        backend, runtime, detected_from, evidence
    )
    supervisor = worker_supervisor.WorkerSupervisor(
        run_dir,
        context,
        herdr_binary=os.environ.get("E2E_HERDR_BINARY", "herdr"),
        tmux_binary=os.environ.get("E2E_TMUX_BINARY", "tmux"),
        paseo_binary=os.environ.get("E2E_PASEO_BINARY", "paseo"),
    )
    # Recovery must use the launch-time identity, including when a crash left
    # only a starting record and the backend handle still needs adoption.
    agent_name = (
        record["agent_name"]
        if record and isinstance(record.get("agent_name"), str) and record["agent_name"]
        else _legacy_agent_name(assignment)
    )
    request = worker_supervisor.WorkerRequest(
        action_id=assignment["action_id"],
        agent_name=agent_name,
        assignment_path=assignment_path.resolve(),
        cwd=Path(assignment["cwd"]),
        timeout_seconds=assignment["timeout_seconds"],
        runtime=runtime,
        prompt=_worker_prompt(assignment_path.resolve()),
        thinking=str(record["thinking"]) if record and record.get("thinking") else effective_thinking(assignment, run),
    )
    recovered = supervisor.recover(request)
    if recovered is not None:
        return recovered
    if record is None and backend == "herdr":
        return supervisor.recover_legacy_herdr(request)
    return None


def retry_worker_cleanups(*, run_dir: Path) -> list[dict[str, Any]]:
    """Retry settled backend cleanup independently of pending graph actions."""
    run_path = run_dir / "run.json"
    if not run_path.is_file():
        return []
    pinned = load_json(run_path).get("worker_execution")
    if not isinstance(pinned, dict):
        return []
    context = worker_supervisor.ExecutionContext(
        pinned["backend"],
        pinned["runtime"],
        pinned.get("detected_from", "run.json"),
        dict(pinned.get("evidence", {})),
    )
    supervisor = worker_supervisor.WorkerSupervisor(
        run_dir,
        context,
        herdr_binary=os.environ.get("E2E_HERDR_BINARY", "herdr"),
        tmux_binary=os.environ.get("E2E_TMUX_BINARY", "tmux"),
        paseo_binary=os.environ.get("E2E_PASEO_BINARY", "paseo"),
    )
    return supervisor.retry_cleanups()


def run_assignment_batch(
    assignment_paths: list[Path],
    *,
    run_dir: Path,
    herdr_binary: str = "herdr",
    pi_binary: str = "pi",
    codex_binary: str = "codex",
    tmux_binary: str = "tmux",
    paseo_binary: str = "paseo",
    worker_runtime: str = "auto",
    worker_backend: str = "auto",
    dry_run: bool = False,
    allow_existing: bool = False,
) -> tuple[int, dict[str, Any]]:
    if not assignment_paths:
        raise ValueError("at least one assignment is required")
    entries: list[dict[str, Any]] = []
    loaded: list[tuple[Path, dict[str, Any]]] = []
    action_ids: set[str] = set()
    run_ids: set[str] = set()
    writer_repositories: set[str] = set()
    for raw_path in assignment_paths:
        path = raw_path.resolve()
        assignment = load_json(path)
        artifact_guard.validate_assignment(assignment)
        if assignment["action_id"] in action_ids:
            raise ValueError(f"duplicate action_id: {assignment['action_id']}")
        action_ids.add(assignment["action_id"])
        run_ids.add(assignment["run_id"])
        if assignment["project_file_access"] == "write":
            repository = assignment["repo_id"]
            if repository in writer_repositories:
                raise ValueError(
                    f"batch would launch more than one project-file writer for {repository}"
                )
            writer_repositories.add(repository)
        output = Path(assignment["output_artifact"])
        if output.exists() and not allow_existing:
            raise ValueError(f"output already exists before launch: {output}")
        loaded.append((path, assignment))
    if len(run_ids) != 1:
        raise ValueError("every assignment in a batch must belong to the same run")
    run_path = run_dir / "run.json"
    run: dict[str, Any] = {}
    if run_path.exists():
        run = load_json(run_path)
        if run.get("run_id") not in run_ids:
            raise ValueError("assignment run_id does not match the supplied run directory")
        artifact_guard.validate_run(run)
        _enforce_user_plan_approval(run, loaded)
    elif any(
        assignment.get("project_file_access") == "write"
        for _, assignment in loaded
    ):
        raise ValueError(
            "project-file writers require run.json with an approved plan review bundle"
        )

    pinned = run.get("worker_execution")
    if isinstance(pinned, dict):
        context = worker_supervisor.ExecutionContext(
            backend=pinned["backend"],
            runtime=pinned["runtime"],
            detected_from=pinned.get("detected_from", "run.json"),
            evidence=dict(pinned.get("evidence", {})),
        )
    else:
        detection_env = dict(os.environ)
        detection_env.update(
            {
                "E2E_HERDR_BINARY": herdr_binary,
                "E2E_TMUX_BINARY": tmux_binary,
                "E2E_PASEO_BINARY": paseo_binary,
            }
        )
        context = worker_supervisor.detect_execution_context(
            environ=detection_env,
            requested_runtime=worker_runtime,
            requested_backend=worker_backend,
        )
    resolved_runtime = context.runtime
    supervisor = worker_supervisor.WorkerSupervisor(
        run_dir,
        context,
        pi_binary=pi_binary,
        codex_binary=codex_binary,
        herdr_binary=herdr_binary,
        tmux_binary=tmux_binary,
        paseo_binary=paseo_binary,
    )
    requests = [
        worker_supervisor.WorkerRequest(
            action_id=assignment["action_id"],
            agent_name=_agent_name(assignment),
            assignment_path=path,
            cwd=Path(assignment["cwd"]),
            timeout_seconds=assignment["timeout_seconds"],
            runtime=resolved_runtime,
            prompt=_worker_prompt(path),
            thinking=effective_thinking(assignment, run),
        )
        for path, assignment in loaded
    ]

    if dry_run:
        for request in requests:
            preview = supervisor.preview(request)
            entries.append(
                {
                    "action_id": request.action_id,
                    "agent_name": request.agent_name,
                    "assignment_path": str(request.assignment_path),
                    "backend": context.backend,
                    "command": preview["command"],
                    "runtime": resolved_runtime,
                    "model": DEFAULT_WORKER_MODEL,
                    "thinking": request.thinking,
                    "status": "dry-run",
                }
            )
        return 0, {
            "generated_at": utc_now(),
            "dry_run": True,
            "execution_context": context.as_dict(),
            "workers": entries,
        }

    log_dir = run_dir / "supervisor"
    log_dir.mkdir(parents=True, exist_ok=True)
    batch_stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    batch_log = log_dir / f"batch-{batch_stamp}-{os.getpid()}.jsonl"
    outcomes = supervisor.run_batch(requests)
    assignments_by_action = {
        assignment["action_id"]: assignment for _path, assignment in loaded
    }
    for outcome in outcomes:
        assignment = assignments_by_action[outcome["action_id"]]
        result = {
            **outcome,
            "output_artifact": assignment["output_artifact"],
            "runtime": resolved_runtime,
            "model": DEFAULT_WORKER_MODEL,
            "thinking": effective_thinking(assignment, run),
            "status": "rejected",
        }
        if outcome["timed_out"]:
            result["status"] = "timeout"
        elif outcome["settled"]:
            output = Path(assignment["output_artifact"])
            try:
                raw = output.read_bytes()
                if len(raw) > artifact_guard.MAX_BYTES[assignment["output_kind"]]:
                    raise artifact_guard.ValidationError("artifact exceeds its size limit")
                value = json.loads(raw)
                value = normalize_worker_artifact(
                    Path(outcome["assignment_path"]),
                    assignment,
                    output,
                    value,
                )
                if output.stat().st_size > artifact_guard.MAX_BYTES[
                    assignment["output_kind"]
                ]:
                    raise artifact_guard.ValidationError(
                        "normalized artifact exceeds its size limit"
                    )
                artifact_guard.CURRENT_ARTIFACT_PATH = output
                artifact_guard.VALIDATORS[assignment["output_kind"]](
                    artifact_guard.obj(value, "$")
                )
                result["status"] = "accepted"
            except (
                OSError,
                UnicodeDecodeError,
                json.JSONDecodeError,
                artifact_guard.ValidationError,
            ) as error:
                result["reason"] = str(error)
                result.update(artifact_guard.rejection_details(error))
        entries.append(result)
        with batch_log.open("a", encoding="utf-8") as handle:
            handle.write(
                json.dumps(
                    {
                        "at": result["ended_at"],
                        "event": "result",
                        "action_id": result["action_id"],
                        "backend": result["backend"],
                        "handle_id": result["handle_id"],
                        "status": result["status"],
                        "reason": result["reason"],
                        "cleanup_status": result["cleanup_status"],
                        "cleanup_error": result["cleanup_error"],
                    },
                    separators=(",", ":"),
                )
                + "\n"
            )

    all_accepted = all(entry["status"] == "accepted" for entry in entries)
    manifest = {
        "generated_at": utc_now(),
        "dry_run": False,
        "batch_log": str(batch_log),
        "execution_context": context.as_dict(),
        "workers": entries,
    }
    return (0 if all_accepted else 1), manifest


def _accepted_paths(run: dict[str, Any]) -> list[Path]:
    paths: set[Path] = set()
    for reference in run.get("accepted_artifacts", {}).values():
        if isinstance(reference, dict) and reference.get("path"):
            paths.add(Path(reference["path"]))
    for repository in run.get("repositories", {}).values():
        for reference in repository.get("accepted_artifacts", {}).values():
            if isinstance(reference, dict) and reference.get("path"):
                paths.add(Path(reference["path"]))
    return sorted(paths)


def render_report(
    *,
    run_dir: Path,
    assignment_path: Path,
    html_path: Path,
    output_path: Path,
) -> dict[str, Any]:
    assignment = load_json(assignment_path)
    artifact_guard.validate_assignment(assignment)
    if assignment["stage"] != "report" or assignment["output_kind"] != "report":
        raise ValueError("assignment must be a report assignment")
    if output_path.resolve() != Path(assignment["output_artifact"]).resolve():
        raise ValueError("output_path must match assignment.output_artifact")
    if output_path.exists():
        raise ValueError(f"refusing to overwrite existing report artifact: {output_path}")
    if html_path.exists():
        raise ValueError(f"refusing to overwrite existing HTML report: {html_path}")

    run = load_json(run_dir / "run.json")
    requirements = load_json(Path(run["requirements_path"]))
    request_text = Path(run["request_path"]).read_text(encoding="utf-8", errors="replace")
    artifacts: list[dict[str, Any]] = []
    high_impact: set[str] = set()
    for path in _accepted_paths(run):
        try:
            artifact = load_json(path)
        except (OSError, ValueError, json.JSONDecodeError):
            continue
        artifacts.append({"path": str(path), "value": artifact})
        if artifact.get("artifact_kind") == "plan":
            high_impact.update(artifact.get("risk_flags", []))
            for mechanism in artifact.get("complexity_mechanisms", []):
                high_impact.add(str(mechanism.get("type", "high-cost mechanism")))

    style = """
:root { color-scheme: light dark; font-family: ui-sans-serif, system-ui, sans-serif; }
body { max-width: 1100px; margin: 2rem auto; padding: 0 1rem 4rem; line-height: 1.5; }
h1, h2, h3 { line-height: 1.2; }
section { border-top: 1px solid #8886; padding-top: 1rem; margin-top: 1.5rem; }
code, pre { font-family: ui-monospace, monospace; }
pre { white-space: pre-wrap; background: #8881; padding: 1rem; border-radius: .5rem; }
table { border-collapse: collapse; width: 100%; }
th, td { border: 1px solid #8885; padding: .5rem; text-align: left; vertical-align: top; }
.badge { display: inline-block; border: 1px solid #8886; border-radius: 999px; padding: .15rem .55rem; margin: .1rem; }
""".strip()
    requirement_rows = []
    requirement_ids: list[str] = []
    for requirement in requirements.get("requirements", []):
        requirement_ids.append(requirement["id"])
        criteria = "<br>".join(html.escape(item) for item in requirement["acceptance_criteria"])
        repos = ", ".join(requirement["repository_ids"])
        requirement_rows.append(
            f"<tr><td><code>{html.escape(requirement['id'])}</code></td>"
            f"<td>{html.escape(requirement['source_text'])}</td>"
            f"<td>{criteria}</td><td>{html.escape(repos)}</td></tr>"
        )

    repo_sections = []
    for repo_id, repository in sorted(run.get("repositories", {}).items()):
        accepted = repository.get("accepted_artifacts", {})
        items = "".join(
            f"<li><code>{html.escape(name)}</code>: {html.escape(reference['path'])}</li>"
            for name, reference in sorted(accepted.items())
        )
        repo_sections.append(
            f"<h3>{html.escape(repo_id)}</h3>"
            f"<p>Branch <code>{html.escape(repository['branch'])}</code> from "
            f"<code>{html.escape(repository['base_branch'])}</code>.</p><ul>{items}</ul>"
        )

    evidence_rows = []
    artifact_details: list[str] = []
    pr_links: list[str] = []
    for item in artifacts:
        value = item["value"]
        summary = value.get("summary") or value.get("status") or "accepted"
        kind = str(value.get("artifact_kind", "unknown"))
        evidence_rows.append(
            f"<tr><td>{html.escape(kind)}</td>"
            f"<td><code>{html.escape(item['path'])}</code></td>"
            f"<td>{html.escape(str(summary))}</td></tr>"
        )
        accepted_json = json.dumps(value, indent=2, ensure_ascii=False)
        artifact_details.append(
            f"<details><summary><strong>{html.escape(kind)}</strong> — "
            f"<code>{html.escape(item['path'])}</code></summary>"
            f"<pre>{html.escape(accepted_json)}</pre></details>"
        )
        if value.get("artifact_kind") == "delivery" and value.get("pr_url"):
            url = html.escape(value["pr_url"], quote=True)
            pr_links.append(f'<li><a href="{url}">{url}</a></li>')

    document = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>{html.escape(run['run_id'])} report</title><style>{style}</style></head><body>
<h1>End-to-end development report</h1>
<p><span class="badge">{html.escape(run.get('profile', 'legacy-full'))}</span>
<span class="badge">{html.escape(run.get('status', 'unknown'))}</span>
<span class="badge">{html.escape(run.get('phase', 'unknown'))}</span></p>
<section><h2>Request</h2><pre>{html.escape(request_text)}</pre></section>
<section><h2>Requirement coverage</h2><table><thead><tr><th>ID</th><th>Source</th><th>Acceptance criteria</th><th>Repositories</th></tr></thead>
<tbody>{''.join(requirement_rows)}</tbody></table></section>
<section><h2>Repositories and accepted changes</h2>{''.join(repo_sections)}</section>
<section><h2>Validation, review, and delivery evidence</h2><table><thead><tr><th>Kind</th><th>Artifact</th><th>Summary</th></tr></thead>
<tbody>{''.join(evidence_rows)}</tbody></table></section>
<section><h2>Accepted artifact details</h2>{''.join(artifact_details) or '<p>No accepted artifacts recorded.</p>'}</section>
<section><h2>Pull requests</h2><ul>{''.join(pr_links) or '<li>None recorded.</li>'}</ul></section>
<section><h2>High-impact topics</h2><p>{' '.join(f'<span class="badge">{html.escape(topic)}</span>' for topic in sorted(high_impact)) or 'None recorded.'}</p></section>
</body></html>\n"""
    html_path.parent.mkdir(parents=True, exist_ok=True)
    html_path.write_text(document, encoding="utf-8")
    report = {
        "schema_version": 1,
        "artifact_kind": "report",
        "run_id": assignment["run_id"],
        "assignment_path": str(assignment_path.resolve()),
        "assignment_sha256": hashlib.sha256(assignment_path.read_bytes()).hexdigest(),
        "created_at": utc_now(),
        "status": "complete",
        "html_path": str(html_path.resolve()),
        "html_size_bytes": html_path.stat().st_size,
        "html_sha256": hashlib.sha256(html_path.read_bytes()).hexdigest(),
        "requirement_ids": sorted(requirement_ids),
        "high_impact_topics": sorted(high_impact),
        "blockers": [],
    }
    atomic_write_json(output_path, report)
    artifact_guard.CURRENT_ARTIFACT_PATH = output_path
    artifact_guard.validate_report(report)
    return report


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    policy = subparsers.add_parser("policy", help="classify a run and emit its workflow policy")
    policy.add_argument("--repository-count", type=int, required=True)
    policy.add_argument("--risk", action="append", default=[])
    policy.add_argument("--profile", choices=["auto", "fast", "standard", "full"], default="auto")
    policy.add_argument("--report", action="store_true")

    fingerprint = subparsers.add_parser("fingerprint", help="hash a Git worktree state")
    fingerprint.add_argument("worktree", type=Path)

    metrics = subparsers.add_parser("metrics", help="summarize run latency")
    metrics.add_argument("run_dir", type=Path)
    metrics.add_argument("--output", type=Path)

    batch = subparsers.add_parser("run-batch", help="launch and wait for immutable assignments")
    batch.add_argument("--run-dir", type=Path, required=True)
    batch.add_argument("--herdr", default="herdr")
    batch.add_argument("--tmux", default="tmux")
    batch.add_argument("--paseo", default="paseo")
    batch.add_argument("--pi", default="pi")
    batch.add_argument("--codex", default="codex")
    batch.add_argument(
        "--worker-backend",
        choices=["auto", *sorted(worker_supervisor.WORKER_BACKENDS)],
        default="auto",
        help=argparse.SUPPRESS,
    )
    batch.add_argument(
        "--worker-runtime",
        choices=sorted(WORKER_RUNTIMES),
        default="auto",
        help="worker CLI; auto follows the coordinator runtime",
    )
    batch.add_argument("--dry-run", action="store_true")
    batch.add_argument("--allow-existing", action="store_true", help=argparse.SUPPRESS)
    batch.add_argument("assignments", nargs="+", type=Path)

    report = subparsers.add_parser("render-report", help="render deterministic HTML from accepted artifacts")
    report.add_argument("--run-dir", type=Path, required=True)
    report.add_argument("--assignment", type=Path, required=True)
    report.add_argument("--html", type=Path, required=True)
    report.add_argument("--output", type=Path, required=True)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    try:
        if args.command == "policy":
            result = workflow_policy(
                repository_count=args.repository_count,
                risk_flags=args.risk,
                requested_profile=args.profile,
                report_requested=args.report,
            )
            print(json.dumps(result, indent=2))
            return 0
        if args.command == "fingerprint":
            print(worktree_fingerprint(args.worktree))
            return 0
        if args.command == "metrics":
            result = run_metrics(args.run_dir)
            if args.output:
                atomic_write_json(args.output, result)
            print(json.dumps(result, indent=2))
            return 0
        if args.command == "run-batch":
            code, result = run_assignment_batch(
                args.assignments,
                run_dir=args.run_dir,
                herdr_binary=args.herdr,
                tmux_binary=args.tmux,
                paseo_binary=args.paseo,
                pi_binary=args.pi,
                codex_binary=args.codex,
                worker_runtime=args.worker_runtime,
                worker_backend=args.worker_backend,
                dry_run=args.dry_run,
                allow_existing=args.allow_existing,
            )
            print(json.dumps(result, indent=2))
            return code
        if args.command == "render-report":
            result = render_report(
                run_dir=args.run_dir,
                assignment_path=args.assignment,
                html_path=args.html,
                output_path=args.output,
            )
            print(json.dumps(result, indent=2))
            return 0
    except (OSError, RuntimeError, ValueError, artifact_guard.ValidationError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
